language: node_js
sudo: false
node_js:
- '5.1'
notifications:
  slack:
    secure: GVfE08sE3k4mrd+URRIVG3CdZj9Jn5p+DepkwYciY2XbRVWx3trhO9Vc6YTZF8zJqCGZILgeNwSUbgtJeZSls9zPkv5HE2f41khg/9ImWaw51z7p74+plmKorgm5Mqk7LrMfEc+dtoSIn62QrMN2jZaMm5wcGU8cwGuHVjJ/psxS/W0MsIxs8lk1Fmxf5R+eO1hsQq+sBfZzlFCgx6eTZhD9ysadMSAledZL9FPNll92J/pDyTU38K2KcfBPJqFxV/zSEI0Ag6aEdcJji57Me43HDHWKNiyjL1egyZTFGCeOsQmZ+0xh70dSSGBKajJelIPI8R6K7t7b/LwBG8UZOwlomejiYq2+i7rtxF1sS2wSKkISnAXCKw5thoURAYqcbQIKO48GD8sl9yZZRRKewqe3RH3scP5QNlknbAUmsPZIG90sIM2RdGPt4IefCl3NRLduxtOe74nvPP04Be8wGL8mKOH13/fDB9NpkHE3nBEokv2t+ms3mx+lE1k7kLJuwaKx0HR3igmdeMZ74Qoko3CRngYM+XS2OhPw5HVe6FbotmElz8N9d8YhOgiEMcS8c4HputaUYEIt7eYv3yey0EbVM+RCBlui1eELu+ecpU/G/dVnUYXAzewo1V6sXoXKwWR50ZYT6czWJzv4ufXIW0wwUU5WVir8jAHvUdkrCrs=
